abstract: Implementation of managesieve protocol to manage sieve scripts
author: Yves Agostini - Univ Metz <agostini@univ-metz.fr>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Net-Sieve
no_index: 
  directory: 
    - inc
    - t
requires: 
  Authen::SASL: 0
  IO::Socket::INET6: 0
  IO::Socket::SSL: 0
  MIME::Base64: 0
tests: t/*.t
version: 0.02
