---
abstract: 'Implementation of managesieve protocol to manage sieve scripts'
author:
  - 'Yves Agostini <yvesago@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Sieve
no_index:
  directory:
    - inc
    - t
requires:
  Authen::SASL: 2.11
  IO::Socket::INET6: 0
  IO::Socket::SSL: 0
  MIME::Base64: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
